name: SPEC.md implementation
on:
  push:
    branches-ignore:
      - main
    paths:
      - 'SPEC.md'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  implementation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: mkdir ~/.codex
      - run: echo $OPENAI_TOKEN > ~/.codex/auth.json
        env:
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
      - run: |
          npx --yes @openai/codex exec --full-auto "Implement a solution described in SPEC.md file. \
          Add Dockerfile for running the solution. The Dockerfile has to be in the root of the repository. \
          Expose solution on port 8000 in Dockerfile."
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: codex version
          title: Implementation by Codex Agent
          body: First version based on spec.md
          branch: codex-version

